model:
  name: gtcrn
  params:
    n_fft: 512
    hop_len: 256
    win_len: 512
DDP:
  world_size: 1
optimizer:
  lr: 0.001
scheduler:
  name: warmup_cosine
  params:
    warmup_steps: 25000
    decay_until_step: 250000
    max_lr: 0.001
    min_lr: 1.0e-06
  update_interval: step
FFT:
  n_fft: 512
  hop_length: 256
  win_length: 512
loss:
  name: hybrid
  params:
    n_fft: ${FFT.n_fft}
    hop_len: ${FFT.hop_length}
    win_len: ${FFT.win_length}
    compress_factor: 0.3
    eps: 1.0e-12
    lamda_ri: 30
    lamda_mag: 70
train_dataset:
  name: voicebank
  params:
    noisy_dir: /input0/noisy_trainset_28spk_wav
    clean_dir: /input0/clean_trainset_28spk_wav
    scp_path: /input0/train.scp
    length_in_seconds: 5
    num_data_per_epoch: 10000
    train: true
train_dataloader:
  batch_size: 128
  num_workers: 8
  drop_last: true
  pin_memory: true
validation_dataset:
  name: voicebank
  params:
    noisy_dir: /input0/noisy_testset_wav
    clean_dir: /input0/clean_testset_wav
    scp_path: /input0/test.scp
    length_in_seconds: 5
    train: false
validation_dataloader:
  batch_size: 32
  num_workers: 4
  pin_memory: true
samplerate: 16000
trainer:
  epochs: 200
  save_checkpoint_interval: 1
  validation_interval: 10
  clip_grad_norm_value: 3.0
  exp_path: ./runs/exp_gtcrn
  resume: false
  resume_datetime: 2026-12-31-14h28m
