
MODEL:
  NAME: NSNET
  INPUT_DIM: 129
  GRU_LAYERS: 3
  GRU_DROPOUT: 0.5
  PRETRAIN_PATH: NONE

LOSSES:
  NAME: ["WeightedSpeechDistortionLoss"]

  WSD:
    SCALE: 1.
    INDEX: 0
    ALPHA: 0.4
    EPS: 1e-7

DATA:
  TRAIN_DIR: ./datasets/data/train/
  VAL_DIR: ./datasets/data/val/
  TEST_DIR: ./datasets/data/test/

  SAMPLE_RATE: 16000
  FRAME_LEN: 128
  HOP_LEN: 128
  N_FFT: 256
  WIN_TYPE: hanning
  NORMALIZE: True

  FEATURE: Spectrum

  NUM_WORKERS: 12
  TRAIN_BATCH_SIZE: 256
  VAL_BATCH_SIZE: 64


SOLVER:
  AMP:
    ENABLED: False
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005

  SCHED: MultiStepLR
  STEPS: [ 40, 90 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 10

TEST:
  EVAL_PERIOD: 10
  BATCH_SIZE: 128

CUDNN_BENCHMARK: True

OUTPUT_DIR: ../outputs/nsnet/

